implements CIS Benchmark - 2.1.2 Ensure chrony is configured
linux-system-roles/timesync pull request #236
Opened 2024-03-29 08:46 UTC by brakkio86

Enhancement:
I changed the template for chrony sysconfig in order to implement CIS Benchmark recomendation for RHEL.

Reason:
Be compatible with CIS Benchmark "2.1.2 Ensure chrony is configured" on a RHEL.

Result:
CIS Benchmark compatible.

Issue Tracker Tickets (Jira or BZ if any):
N.A.

2024-04-02 09:06 UTC, spetrosi commented
[citest]

2024-04-02 09:12 UTC, mlichvar commented
`-u chrony` is the default on RHEL. It doesn't need to be set. Other distributions may have different names for the user.

2024-04-02 13:18 UTC, richm requested changes
Thanks @mlichvar - so the PR as it stands needs some work so that it will only set `-u chrony` on those platforms that do not set a default user.

2024-04-03 06:34 UTC, brakkio86 commented
Hello, in RHEL the compiled-in default user is "chrony" user, on the other hand, CIS benchmark want to be sure that is also the effective configuration. Is it possible to add a check in order to implements it only on RHEL. Another way to allow the implementation is to allow to customization of the sysconfig file.
Thanks,
Francesco

2024-04-04 07:39 UTC, brakkio86 commented
> > Hello, in RHEL the compiled-in default user is "chrony" user, on the other hand, CIS benchmark want to be sure that is also the effective configuration. Is it possible to add a check in order to implements it only on RHEL. Another way to allow the implementation is to allow to customization of the sysconfig file. Thanks, Francesco
> 
> I'm not sure what you are trying to do. Are you running some sort of CIS compliance scanner that is complaining that chronyd is not using `-u chrony`? If so, then it seems to be that the right answer isn't to force `-u chrony` using this role.

Yes, I'm appling CIS compliant configuration. On the other hand, this role broke the configuation as it removes  `-u chrony` settings. What do you suggest?

2024-04-04 13:24 UTC, richm commented
> > > Hello, in RHEL the compiled-in default user is "chrony" user, on the other hand, CIS benchmark want to be sure that is also the effective configuration. Is it possible to add a check in order to implements it only on RHEL. Another way to allow the implementation is to allow to customization of the sysconfig file. Thanks, Francesco
> > 
> > 
> > I'm not sure what you are trying to do. Are you running some sort of CIS compliance scanner that is complaining that chronyd is not using `-u chrony`? If so, then it seems to be that the right answer isn't to force `-u chrony` using this role.
> 
> Yes, I'm appling CIS compliant configuration. On the other hand, this role broke the configuation as it removes `-u chrony` settings. What do you suggest?

Well, as @mlichvar says, the default on RHEL is `-u chrony`.  So for CIS compliance, do you just need a way to determine what that default value is?

2024-04-09 08:58 UTC, brakkio86 commented
> Well, as @mlichvar says, the default on RHEL is `-u chrony`. So for CIS compliance, do you just need a way to determine what that default value is?

Unfotunally no, CIS Security mandatory requires explicit user in `/etc/sysconfig/chronyd`. Maybe is it possbible to parametrize `OPTIONS` section in `/etc/sysconfig/chronyd`.

2024-04-10 12:36 UTC, brakkio86 commented on templates/chronyd.sysconfig.j2
> +OPTIONS="-u chrony"
Thanks @richm, I like your hint! I hope that now is good for approval. Thanks, Francesco

2024-04-10 12:38 UTC, mlichvar commented
If a new option needs to be added to the role for this, I'd prefer a more general approach specifying directly the additional chronyd options included in /etc/sysconfig/chronyd, e.g. `timesync_chronyd_custom_options`.

2024-04-10 13:15 UTC, richm commented
> If a new option needs to be added to the role for this, I'd prefer a more general approach specifying directly the additional chronyd options included in /etc/sysconfig/chronyd, e.g. `timesync_chronyd_custom_options`.

The role already has `timesync_chrony_custom_settings` - so maybe `timesync_chrony_sysconfig_settings` for settings applied to `/etc/sysconfig/chrony`?

2024-04-10 13:46 UTC, mlichvar commented
Some systems don't have sysconfig, e.g. on Debian the options are in `/etc/default/chrony`, so the I think the name should be general enough to work on all potentially supported distros.

2024-04-10 13:51 UTC, richm commented
> Some systems don't have sysconfig, e.g. on Debian the options are in `/etc/default/chrony`, so the I think the name should be general enough to work on all potentially supported distros.

Ok - what about `timesync_chrony_service_settings`?

2024-04-12 09:38 UTC, brakkio86 commented
Hello, I've updated with the suggestion and using `timesync_chrony_service_settings`. What do you think now?

2024-06-10 15:47 UTC, richm approved these changes

2024-06-10 15:49 UTC, richm commented
[citest]

2024-06-10 15:51 UTC, richm commented
How can we test this? e.g. add or modify a test in https://github.com/linux-system-roles/timesync/tree/main/tests ?

2024-06-10 15:53 UTC, richm commented
I had to close and reopen the PR to trigger checks - not sure why the checks were not being run . . .

2024-08-01 22:20 UTC, richm commented
Need a test for this in tests/

2025-05-30 21:43 UTC, closed without merging